on:
    push:
        paths:
        - apps/**
        branches:         
        - master 

    pull_request:
      paths:
      - apps/**
           
  
  name: CI workflow
  
  
  env:
    AWS_DEFAULT_REGION: eu-west-3
    AWS_DEFAULT_OUTPUT: json
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    CONTAINER_IMAGE: demo-eks:${{ github.sha }}
  
  jobs:
    build-and-push:
      name: Build and deploy
      runs-on: ubuntu-latest
      steps:
  
      - name: Checkout
        uses: actions/checkout@master
  
              
      - name: Setup ECR
        run: |
          $( aws ecr get-login --no-include-email )
      - name: Build and tag the image
        run: |
            docker build \
            -t $CONTAINER_IMAGE \
            -t $GITHUB_REPOSITORY:$GITHUB_SHA \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE ./app
  
      - name: Push
        if: github.ref == 'refs/heads/master'
        run: |
          # Push image to AWS ECR
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE